language: go
cache:
  - apt: true
  - directories:
    - $HOME/.gvm
install:
  - bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

script:
  - $HOME/.gvm/scripts/gvm version
  - $HOME/.gvm/scripts/gvm install go1.4
  - go test tests/*_test.go