language: go
go:
    - 1.2
    - 1.3
    - 1.4
    - tip
cache:
  - apt: true

install:
  - sudo apt-get install -y curl bison make
  - go get golang.org/x/tools/cmd/vet

script:
  - go vet
  - go build
  - make check
  - make test
  - make bench
