language: go
sudo: required
dist: trusty

before_script:
  - mount > build_debug.log
  - echo $TRAVIS_BUILD_DIR >> build_debug.log
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull bbiskup/edify_dev:latest || true
  - make

script:
  - ./docker-cmd.sh ./scripts/run-checks.sh 

after_success:
  - docker tag -f edify_dev bbiskup/edify_dev:latest
  - docker  tag edify_dev bbiskup/edify_dev:$TRAVIS_BUILD_NUMBER
  - docker push bbiskup/edify_dev:latest
  - docker push bbiskup/edify_dev:$TRAVIS_BUILD_NUMBER
