language: go
cache:
  - apt: true
  - directories:
    - $HOME/.gvm

install:
  - sudo apt-get install -y curl
  - bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer) || true
  - sudo mkdir -p /usr/local/go

script:
  - . $HOME/.gvm/scripts/gvm && gvm version
  - . $HOME/.gvm/scripts/gvm && gvm install go1.4
  - go test tests/*_test.go