language: go
go:
    - 1.2
    - 1.3
    - 1.4
    - tip
cache:
  - apt: true

install:
  - sudo apt-get install -y curl bison

script:
  - go test -v tests/*_test.go
  - go test -v -bench . tests/*_test.go