language: go
go:
    - 1.2
    - 1.3
    - 1.4
    - tip
cache:
  #- apt: true

install:
  - sudo apt-get update -y
  - sudo apt-get install -y curl bison make
  - go get golang.org/x/tools/cmd/vet

script:
  - go clean
  - make get-deps
  - make get-test-deps
  - go vet
  - go build
  - make check
  - make test-multi-cpu

  - # avoid excessive output
  - make bench 2> bench.log
  
  - time ./edify download_specs 14b
  - time ./edify extract_specs 14b
  - time ./edify purge_specs 14b
  - time ./edify ./edify parse testdata/UNCL.14B
  - time ./edify ./edify full_parse testdata/d14b/
  # - time ./edify ./edify parse testdata/EDED.14B
  # - time ./edify ./edify parse testdata/EDCD.14B

  - make cover